### ISSUE TITLE
Graphical issues in Whomp's Fortress

### ISSUE THREAD

**Issue by DPS2004** [sm64-port/sm64_3ds#14]
Hello

Early in the stage "Whomp's Fortress", there are some graphical glitches. Lines are appearing in between polygons in what I assume is a glitch.

![sm64](https://user-images.githubusercontent.com/10176105/89126359-15e84700-d4b3-11ea-81fd-d06dd266b92a.png)
I tried to take a screenshot with Luma3DS, but it only captured half of the screen. But even on this screenshot, you can still see the lines.

**Comment by vaguerant** [comment]
Not relevant to yours issue, but if you update your Luma3DS version

**Comment by vaguerant** [comment]
Not relevant to your issue, but if you update your Luma3DS install, you will be able to take 800px screenshots, as used in sm64_3ds.

**Comment by DPS2004** [comment]
Good to know! Will update and try taking another screenshot

**Comment by NepDisk** [comment]
I believe that those lines are just part of the original level because it can be seen on other sm64 ports
heres a picture of this issue in the pc port also, I think the original level just has them for some reason
![image](https://user-images.githubusercontent.com/16447892/89241278-6a331a00-d5cc-11ea-8b6d-2dcd9068043a.png)

**Comment by DPS2004** [comment]
Huh, interesting! Someone should make a mod to fix this, but I would guess that this is probably out of the scope for this specific port.

**Comment by 64emax** [comment]
I think it's because those platforms are actually objects and not part of the level for some reason, so there isn't 100% precision in positioning
